#ifndef CONSTANTS
#define CONSTANTS

#define TARGET_FPS 24
#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 800

enum Levels {LEVEL_GRASS, LEVEL_WATER, LEVEL_ICE, LEVEL_SPACE, LEVEL_VOLCANO, LEVEL_CASTLE};
enum Directions {DIR_UP, DIR_DOWN, DIR_LEFT, DIR_RIGHT};
enum Music
{
  MUSIC_INTRO,
  MUSIC_HOME,
  MUSIC_MENU,
  MUSIC_GRASS,
  MUSIC_GRASS_BOSS,
  MUSIC_WATER,
  MUSIC_WATER_BOSS,
  MUSIC_ICE,
  MUSIC_ICE_BOSS,
  MUSIC_SPACE,
  MUSIC_SPACE_BOSS,
  MUSIC_VOLCANO,
  MUSIC_VOLCANO_BOSS,
  MUSIC_CASTLE,
  MUSIC_CASTLE_BOSS,
  MUSIC_WIN,
  MUSIC_LOSE
};
enum Sfx
{
  SFX_JUMP,
  SFX_HIT,
  SFX_COIN
};

#endif
